# Visualizations

To cover the first of this project goals, "*to construct a web dashboard to visualize the evolution of the main air pollution indicators of Gijon city*" I chose as main tool the [Tableau](https://www.tableau.com/) software. 

I created a Tableau story for each pollutant with Tableau Desktop (student license). And I published them on my [Tableau Public personal site](https://public.tableau.com/profile/sergioberdiales#!/). 

Each story shows a brief description of each pollutant, the evolution of its levels during the last two decades, the non-compliance with the EU standards or the WHO advice, several visualizations to show its seasonal components, etc. 

The datasets used on these visualizations were prepared with R code. You can consult this code in the section ***** of this document or in the Github repository of this project *****. 

__Tableau Public stories__:

If you want to consult the published stories you only have to click on the links below:

* [Pollutant PM10 story](https://public.tableau.com/views/ContaminacinaireGijncontaminantePM10/PM10_story?:embed=y&:display_count=yes)


* [Pollutant PM25 story](https://public.tableau.com/views/ContaminacinaireGijn5contaminantePM25/PM25_story?:embed=y&:display_count=yes&publish=yes)


* [Pollutant NO2 story](https://public.tableau.com/views/ContaminacinaireGijn2contaminanteNO2/NO2_story?:retry=yes&:embed=y&:display_count=yes)


* [Pollutant SO2 story](https://public.tableau.com/views/ContaminacinaireGijn3contaminanteSO2/SO2_story?:embed=y&:display_count=yes)


* [Pollutant CO story](https://public.tableau.com/shared/S9K29CBNG?:display_count=yes)  


* [Pollutant O3 story](https://public.tableau.com/views/ContaminacinaireGijn6contaminanteO3/O3_story?:embed=y&:display_count=yes)  

The data visualization is a basic but powerful tool for any data science project. So, beyond the Tableau dashboards, I used the graphical visualizations of data for very different purposes. From basic data exploration - looking for quality data problems -, to look for data trends and seasonality or to check graphically the accuracy of a model. 

Some of these visualizations are included in this document but most of them are embedded in the R and Python code.

  
  
