---
title: "Train / Test datasets PM10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading packages
```{r , warning= FALSE, message= FALSE}
library(readr)
library(dplyr)
library(tidyr)
#library(openair) # http://davidcarslaw.github.io/openair/
library(purrr)
library(lubridate)
library(ggplot2)
library(stringr)
library(knitr)
#library(xts)
#library(zoo)
library(gridExtra)
#library(astsa)
#library(rvest)
#library(fpp2)
library(ranger)
library(broom)
library(RcppRoll)
#library(caret)
```


### Modelos a 1 hora
```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}
air_data_2 <- readRDS("data_rds_files/air_data_2.rds")
constitucion_data <- air_data_2 %>% filter(station == "1") 

argentina_data <- air_data_2 %>% filter(station == "2")

pm10_1_argentina <- argentina_data %>% select(date_time_utc, PM10) %>%
                                       mutate(PM10_1_arg = lag(PM10, 1)) %>%
                                       select(date_time_utc, PM10_1_arg)

constitucion_data <- constitucion_data %>% left_join(pm10_1_argentina, by = "date_time_utc")

#constitucion_data <- readRDS("constitucion_data.rds")
constitucion_data$hour <- as.factor(constitucion_data$hour)
constitucion_data$week_day <- as.factor(constitucion_data$week_day)
constitucion_data$month <- as.factor(constitucion_data$month)




train_2014_2016 <- constitucion_data %>% filter(year > 2013, 
                                        year < 2017) %>% 
                                        select(PM10, PM10_1_arg, PM25, NO2, SO2, hour, week_day, month, lab, vv, wd) %>% 
                                        rename(PM10_0 = PM10,
                                               NO2_0 = NO2,
                                               SO2_0 = SO2,
                                               vv_0 = vv,
                                               wd_0 = wd,
                                               PM25_0 = PM25) %>%
                                        na.omit()



test_201701_201709 <- constitucion_data %>% filter(date_time_utc >= '2017-01-01 00:00:00',
                                       date_time_utc < '2017-10-01 00:00:00') %>%
                                       select(PM10,PM10_1_arg,  PM25, NO2, SO2, hour, week_day, month, lab, vv, wd) %>%
                                       rename(PM10_0 = PM10,
                                               NO2_0 = NO2,
                                               SO2_0 = SO2,
                                               vv_0 = vv,
                                               wd_0 = wd,
                                               PM25_0 = PM25) %>%
                                       na.omit()



# We create the PM10, SO2, and NO2 lagged variables

train_2014_2016 <- train_2014_2016 %>% mutate(PM10_1 = lag(PM10_0, 1),
                                              PM10_2 = lag(PM10_0, 2),
                                              PM10_3 = lag(PM10_0, 3),
                                              PM10_4 = lag(PM10_0, 4),
                                              NO2_1 = lag(NO2_0, 1),
                                              NO2_2 = lag(NO2_0, 2),
                                              NO2_3 = lag(NO2_0, 3),
                                              NO2_4 = lag(NO2_0, 4),
                                              SO2_1 = lag(SO2_0, 1),
                                              SO2_2 = lag(SO2_0, 2),
                                              SO2_3 = lag(SO2_0, 3),
                                              SO2_4 = lag(SO2_0, 4),
                                              vv_1 = lag(vv_0, 1),
                                              vv_2 = lag(vv_0, 2),
                                              vv_3 = lag(vv_0, 3),
                                              vv_4 = lag(vv_0, 4),
                                              wd_1 = lag(wd_0, 1),
                                              wd_2 = lag(wd_0, 2),
                                              wd_3 = lag(wd_0, 3),
                                              wd_4 = lag(wd_0, 4),
                                              PM25_1 = lag(PM25_0,1)) %>%
                                              na.omit()


test_201701_201709 <- test_201701_201709 %>% mutate(PM10_1 = lag(PM10_0, 1),
                                              PM10_2 = lag(PM10_0, 2),
                                              PM10_3 = lag(PM10_0, 3),
                                              PM10_4 = lag(PM10_0, 4),
                                              NO2_1 = lag(NO2_0, 1),
                                              NO2_2 = lag(NO2_0, 2),
                                              NO2_3 = lag(NO2_0, 3),
                                              NO2_4 = lag(NO2_0, 4),
                                              SO2_1 = lag(SO2_0, 1),
                                              SO2_2 = lag(SO2_0, 2),
                                              SO2_3 = lag(SO2_0, 3),
                                              SO2_4 = lag(SO2_0, 4),
                                              vv_1 = lag(vv_0, 1),
                                              vv_2 = lag(vv_0, 2),
                                              vv_3 = lag(vv_0, 3),
                                              vv_4 = lag(vv_0, 4),
                                              wd_1 = lag(wd_0, 1),
                                              wd_2 = lag(wd_0, 2),
                                              wd_3 = lag(wd_0, 3),
                                              wd_4 = lag(wd_0, 4),
                                              PM25_1 = lag(PM25_0,1)) %>%
                                              na.omit() 


```

Exportamos train y test como csvs para subirlos a Google Colab y montar los modelos con Python. 

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}

y_train_2014_2016 <- train_2014_2016 %>% select(PM10_0)
X_train_2014_2016 <- train_2014_2016 %>% select(-PM10_0, -NO2_0, -SO2_0, -vv_0, -wd_0, -PM25_0)

write_csv(X_train_2014_2016, "train_test_csvs/X_train_2014_2016.csv")
write_csv(y_train_2014_2016, "train_test_csvs/y_train_2014_2016.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(PM10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-PM10_0,  -NO2_0, -SO2_0, -vv_0, -wd_0, -PM25_0)

write_csv(X_test_201701_201709, "train_test_csvs/X_test_201701_201709.csv")
write_csv(y_test_201701_201709, "train_test_csvs/y_test_201701_201709.csv")


```

Export to Google Drive

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}


y_train_2016_q4 <- train_2016_q4 %>% select(PM10_0)
X_train_2016_q4 <- train_2016_q4 %>% select(-PM10_0)

write_csv(X_train_2016_q4, "train_test_csvs/X_train_2016_q4.csv")
write_csv(y_train_2016_q4, "train_test_csvs/y_train_2016_q4.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(PM10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-PM10_0)

write_csv(X_test_201701_201709, "train_test_csvs/X_test_201701_201709.csv")
write_csv(y_test_201701_201709, "train_test_csvs/y_test_201701_201709.csv")



```

### Modelos a 6 horas
```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}
air_data_2 <- readRDS("data_rds_files/air_data_2.rds")
constitucion_data <- air_data_2 %>% filter(station == "1") 
#constitucion_data <- readRDS("constitucion_data.rds")
constitucion_data$hour <- as.factor(constitucion_data$hour)
constitucion_data$week_day <- as.factor(constitucion_data$week_day)
constitucion_data$month <- as.factor(constitucion_data$month)


train_2014_2016 <- constitucion_data %>% filter(year > 2013, 
                                        year < 2017) %>% 
                                        select(PM10, NO2, SO2, hour, week_day, month, lab, vv, wd) %>% 
                                        rename(PM10_0 = PM10,
                                               NO2_0 = NO2,
                                               SO2_0 = SO2,
                                               vv_0 = vv,
                                               wd_0 = wd) %>%
                                        na.omit()



test_201701_201709 <- constitucion_data %>% filter(date_time_utc >= '2017-01-01 00:00:00',
                                       date_time_utc < '2017-10-01 00:00:00') %>%
                                       select(PM10, NO2, SO2, hour, week_day, month, lab, vv, wd) %>%
                                       rename(PM10_0 = PM10,
                                               NO2_0 = NO2,
                                               SO2_0 = SO2,
                                               vv_0 = vv,
                                               wd_0 = wd) %>% 
                                                na.omit()



# We create the PM10, SO2, and NO2 lagged variables

train_2014_2016 <- train_2014_2016 %>% mutate(PM10_7 = lag(PM10_0, 7),
                                              PM10_8 = lag(PM10_0, 8),
                                              PM10_9 = lag(PM10_0, 9),
                                              PM10_10 = lag(PM10_0, 10),
                                              PM10_23 = lag(PM10_0, 23),
                                              PM10_24 = lag(PM10_0, 24),
                                              PM10_25 = lag(PM10_0, 25),
                                              NO2_7 = lag(NO2_0, 7),
                                              NO2_8 = lag(NO2_0, 8),
                                              NO2_9 = lag(NO2_0, 9),
                                              NO2_10 = lag(NO2_0, 10),
                                              SO2_7 = lag(SO2_0, 7),
                                              SO2_8 = lag(SO2_0, 8),
                                              SO2_9 = lag(SO2_0, 9),
                                              SO2_10 = lag(SO2_0, 10),
                                              vv_7 = lag(vv_0, 7),
                                              vv_8 = lag(vv_0, 8),
                                              vv_9 = lag(vv_0, 9),
                                              vv_10 = lag(vv_0, 10),
                                              wd_7 = lag(wd_0, 7),
                                              wd_8 = lag(wd_0, 8),
                                              wd_9 = lag(wd_0, 9),
                                              wd_10 = lag(wd_0, 10)) %>%
                                                na.omit()


test_201701_201709 <- test_201701_201709 %>% mutate(PM10_7 = lag(PM10_0, 7),
                                              PM10_8 = lag(PM10_0, 8),
                                              PM10_9 = lag(PM10_0, 9),
                                              PM10_10 = lag(PM10_0, 10),
                                              PM10_23 = lag(PM10_0, 23),
                                              PM10_24 = lag(PM10_0, 24),
                                              PM10_25 = lag(PM10_0, 25),
                                              NO2_7 = lag(NO2_0, 7),
                                              NO2_8 = lag(NO2_0, 8),
                                              NO2_9 = lag(NO2_0, 9),
                                              NO2_10 = lag(NO2_0, 10),
                                              SO2_7 = lag(SO2_0, 7),
                                              SO2_8 = lag(SO2_0, 8),
                                              SO2_9 = lag(SO2_0, 9),
                                              SO2_10 = lag(SO2_0, 10),
                                              vv_7 = lag(vv_0, 7),
                                              vv_8 = lag(vv_0, 8),
                                              vv_9 = lag(vv_0, 9),
                                              vv_10 = lag(vv_0, 10),
                                              wd_7 = lag(wd_0, 7),
                                              wd_8 = lag(wd_0, 8),
                                              wd_9 = lag(wd_0, 9),
                                              wd_10 = lag(wd_0, 10)) %>%
                                              na.omit() 


```

Exportamos train y test como csvs para subirlos a Google Colab y montar los modelos con Python. 

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}

y_train_2014_2016 <- train_2014_2016 %>% select(PM10_0)
X_train_2014_2016 <- train_2014_2016 %>% select(-PM10_0, -NO2_0, -SO2_0, -vv_0, -wd_0)

write_csv(X_train_2014_2016, "train_test_csvs/X_train_2014_2016_6h.csv")
write_csv(y_train_2014_2016, "train_test_csvs/y_train_2014_2016_6h.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(PM10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-PM10_0,  -NO2_0, -SO2_0, -vv_0, -wd_0)

write_csv(X_test_201701_201709, "train_test_csvs/X_test_201701_201709_6h.csv")
write_csv(y_test_201701_201709, "train_test_csvs/y_test_201701_201709_6h.csv")


```

Export to Google Drive

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}


y_train_2016_q4 <- train_2016_q4 %>% select(PM10_0)
X_train_2016_q4 <- train_2016_q4 %>% select(-PM10_0)

write_csv(X_train_2016_q4, "train_test_csvs/X_train_2016_q4.csv")
write_csv(y_train_2016_q4, "train_test_csvs/y_train_2016_q4.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(PM10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-PM10_0)

write_csv(X_test_201701_201709, "train_test_csvs/X_test_201701_201709.csv")
write_csv(y_test_201701_201709, "train_test_csvs/y_test_201701_201709.csv")



```

