---
title: "_train_test_old_scripts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```











Exportamos train_1 y test_1 como csvs para subirlos a Google Colab y montar los modelos con Python. 




Export to Google Drive

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}


y_train_2016_q4 <- train_2016_q4 %>% select(pm10_0)
X_train_2016_q4 <- train_2016_q4 %>% select(-pm10_0)

write_csv(X_train_2016_q4, "train_test_csvs/X_train_2016_q4.csv")
write_csv(y_train_2016_q4, "train_test_csvs/y_train_2016_q4.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(pm10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-pm10_0)

write_csv(X_test_201701_201709, "train_test_csvs/X_test_201701_201709.csv")
write_csv(y_test_201701_201709, "train_test_csvs/y_test_201701_201709.csv")



```




Incorporando nuevas variables

La hora del dia


```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}

constitucion_data <- readRDS("constitucion_data.rds")
constitucion_data$hour <- as.factor(constitucion_data$hour)
constitucion_data$week_day <- as.factor(constitucion_data$week_day)
constitucion_data$month <- as.factor(constitucion_data$month)


train_2014_2016 <- constitucion_data %>% filter(year > 2013, 
                                        year < 2017) %>% 
                                        select(PM10, hour, week_day, month) %>% 
                                        rename(pm10_0 = PM10) %>%
                                        na.omit()



test_201701_201709 <- constitucion_data %>% filter(date_time_utc >= '2017-01-01 00:00:00',
                                       date_time_utc < '2017-10-01 00:00:00') %>%
                                       select(PM10, hour, week_day, month) %>%
                                       rename(pm10_0 = PM10) %>%
                                       na.omit()



# We create the PM10 lagged variables

train_2014_2016 <- train_2014_2016 %>% mutate(pm10_1 = lag(pm10_0, 1),
                  pm10_2 = lag(pm10_0, 2),
                  pm10_3 = lag(pm10_0, 3),
                  pm10_4 = lag(pm10_0, 4),) %>%
  na.omit()


test_201701_201709 <- test_201701_201709 %>% mutate(pm10_1 = lag(pm10_0, 1),
                  pm10_2 = lag(pm10_0, 2),
                  pm10_3 = lag(pm10_0, 3),
                  pm10_4 = lag(pm10_0, 4),) %>%
  na.omit()


```

Exportamos train y test como csvs para subirlos a Google Colab y montar los modelos con Python. 

```{r warning = FALSE, message= FALSE, out.width= '\\textwidth'}

y_train_2014_2016 <- train_2014_2016 %>% select(pm10_0)
X_train_2014_2016 <- train_2014_2016 %>% select(-pm10_0)

write_csv(X_train_2014_2016, "train_test_csvs/var_month_X_train_2014_2016.csv")
write_csv(y_train_2014_2016, "train_test_csvs/var_month_y_train_2014_2016.csv")

y_test_201701_201709 <- test_201701_201709 %>% select(pm10_0)
X_test_201701_201709 <- test_201701_201709 %>% select(-pm10_0)

write_csv(X_test_201701_201709, "train_test_csvs/var_month_X_test_201701_201709.csv")
write_csv(y_test_201701_201709, "train_test_csvs/var_month_y_test_201701_201709.csv")



```
