<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>7 Data Exploration | Gijón Air Pollution - An exercise of visualization and forecasting</title>
  <meta name="description" content="7 Data Exploration | Gijón Air Pollution - An exercise of visualization and forecasting">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="7 Data Exploration | Gijón Air Pollution - An exercise of visualization and forecasting" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Data Exploration | Gijón Air Pollution - An exercise of visualization and forecasting" />
  
  
  

<meta name="author" content="Sergio Berdiales">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="gathering-and-cleaning-data.html">
<link rel="next" href="forecasting-models-arima.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#why"><i class="fa fa-check"></i><b>1.1</b> Why</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#what"><i class="fa fa-check"></i><b>1.2</b> What</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#how"><i class="fa fa-check"></i><b>1.3</b> How</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-data.html"><a href="the-data.html"><i class="fa fa-check"></i><b>2</b> The Data</a></li>
<li class="chapter" data-level="3" data-path="visualizations.html"><a href="visualizations.html"><i class="fa fa-check"></i><b>3</b> Visualizations</a></li>
<li class="chapter" data-level="4" data-path="forecasting-models.html"><a href="forecasting-models.html"><i class="fa fa-check"></i><b>4</b> Forecasting Models</a><ul>
<li class="chapter" data-level="4.1" data-path="forecasting-models.html"><a href="forecasting-models.html#pm10-forecasts"><i class="fa fa-check"></i><b>4.1</b> PM10 forecasts</a><ul>
<li class="chapter" data-level="" data-path="forecasting-models.html"><a href="forecasting-models.html#arima-results"><i class="fa fa-check"></i>ARIMA results</a></li>
<li class="chapter" data-level="" data-path="forecasting-models.html"><a href="forecasting-models.html#machine-learning-results"><i class="fa fa-check"></i>Machine Learning results</a></li>
<li class="chapter" data-level="" data-path="forecasting-models.html"><a href="forecasting-models.html#neural-networks"><i class="fa fa-check"></i>Neural Networks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusions.html"><a href="conclusions.html"><i class="fa fa-check"></i><b>5</b> Conclusions</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li><a href="r-scripts.html#r-scripts"><em>R scripts</em></a></li>
<li class="chapter" data-level="6" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html"><i class="fa fa-check"></i><b>6</b> Gathering and Cleaning Data</a><ul>
<li class="chapter" data-level="6.1" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#data-gathering"><i class="fa fa-check"></i><b>6.1</b> Data gathering</a></li>
<li class="chapter" data-level="6.2" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#data-cleaning"><i class="fa fa-check"></i><b>6.2</b> Data cleaning</a></li>
<li class="chapter" data-level="6.3" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#adding-new-variables"><i class="fa fa-check"></i><b>6.3</b> Adding new variables</a><ul>
<li class="chapter" data-level="6.3.1" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#time-variables"><i class="fa fa-check"></i><b>6.3.1</b> Time variables</a></li>
<li class="chapter" data-level="6.3.2" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#laboral-dates"><i class="fa fa-check"></i><b>6.3.2</b> Laboral dates</a></li>
<li class="chapter" data-level="6.3.3" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#wind-direction"><i class="fa fa-check"></i><b>6.3.3</b> Wind direction</a></li>
<li class="chapter" data-level="6.3.4" data-path="gathering-and-cleaning-data.html"><a href="gathering-and-cleaning-data.html#tables-preparation-for-tableau-dashboards"><i class="fa fa-check"></i><b>6.3.4</b> Tables preparation for Tableau dashboards</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>7</b> Data Exploration</a><ul>
<li class="chapter" data-level="7.1" data-path="data-exploration.html"><a href="data-exploration.html#pm10-constitucion-station"><i class="fa fa-check"></i><b>7.1</b> PM10 Constitucion Station</a></li>
<li class="chapter" data-level="7.2" data-path="data-exploration.html"><a href="data-exploration.html#relationships-between-variables"><i class="fa fa-check"></i><b>7.2</b> Relationships between variables</a></li>
<li class="chapter" data-level="7.3" data-path="data-exploration.html"><a href="data-exploration.html#no2-constitucion-station"><i class="fa fa-check"></i><b>7.3</b> NO2 Constitucion Station</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html"><i class="fa fa-check"></i><b>8</b> Forecasting models. ARIMA</a><ul>
<li class="chapter" data-level="8.0.1" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#data-loading"><i class="fa fa-check"></i><b>8.0.1</b> Data loading</a></li>
<li class="chapter" data-level="8.0.2" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10-forecasting-models"><i class="fa fa-check"></i><b>8.0.2</b> PM10 forecasting models</a></li>
<li class="chapter" data-level="8.0.3" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#train-test-and-validation-data-pm10-models"><i class="fa fa-check"></i><b>8.0.3</b> Train, test and validation data (PM10 models)</a></li>
<li class="chapter" data-level="8.0.4" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#data-exploration-1"><i class="fa fa-check"></i><b>8.0.4</b> Data Exploration</a></li>
<li class="chapter" data-level="8.1" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#base-model."><i class="fa fa-check"></i><b>8.1</b> Base model.</a></li>
<li class="chapter" data-level="8.2" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10-arima-models"><i class="fa fa-check"></i><b>8.2</b> PM10 ARIMA models</a><ul>
<li class="chapter" data-level="8.2.1" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10_model_arima_3m"><i class="fa fa-check"></i><b>8.2.1</b> PM10_model_arima_3m</a></li>
<li class="chapter" data-level="8.2.2" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10_model_arima_3y"><i class="fa fa-check"></i><b>8.2.2</b> PM10_model_arima_3y</a></li>
<li class="chapter" data-level="8.2.3" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10_model_arima_9y"><i class="fa fa-check"></i><b>8.2.3</b> PM10_model_arima_9y</a></li>
<li class="chapter" data-level="8.2.4" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10-h-6"><i class="fa fa-check"></i><b>8.2.4</b> PM10 h = 6</a></li>
<li class="chapter" data-level="8.2.5" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10-h-12"><i class="fa fa-check"></i><b>8.2.5</b> PM10 h = 12</a></li>
<li class="chapter" data-level="8.2.6" data-path="forecasting-models-arima.html"><a href="forecasting-models-arima.html#pm10-h-24"><i class="fa fa-check"></i><b>8.2.6</b> PM10 h = 24</a></li>
</ul></li>
</ul></li>
<li><a href="python-scripts.html#python-scripts"><em>Python scripts</em></a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Gijón Air Pollution - An exercise of visualization and forecasting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-exploration" class="section level1">
<h1><span class="header-section-number">7</span> Data Exploration</h1>
<p>Loading packages</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(tidyr)
<span class="kw">library</span>(openair) <span class="co"># http://davidcarslaw.github.io/openair/</span>
<span class="kw">library</span>(purrr)
<span class="kw">library</span>(lubridate)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(stringr)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(xts)
<span class="kw">library</span>(zoo)
<span class="kw">library</span>(gridExtra)
<span class="kw">library</span>(astsa)
<span class="kw">library</span>(rvest)
<span class="kw">library</span>(fpp2)
<span class="kw">library</span>(ranger)
<span class="kw">library</span>(broom)
<span class="kw">library</span>(RcppRoll)
<span class="kw">library</span>(reshape2)</code></pre></div>
<p>Data loading</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">air_data_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data_rds/air_data_2.rds&quot;</span>)</code></pre></div>
<p>We take a look to the general trend of several indicators through the last 18 years</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We calcule the yearly mean of the pollutants levels.</span>
year_avgs &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(station_alias, date_time_utc, PM10, PM25, SO2, NO2, NO, O3, BEN, CO, MXIL, TOL) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(station_alias, <span class="dt">year =</span> <span class="kw">year</span>(date_time_utc)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">funs</span>(<span class="kw">mean</span>(., <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>date_time_utc) <span class="co"># We drop this variable</span>

<span class="co"># We export the years_avgs as a csv file</span>

<span class="kw">write_csv</span>(year_avgs, <span class="st">&quot;data_final_csvs/year_avgs.csv&quot;</span>)

<span class="co"># We convert the table to long format</span>

year_avgs_long &lt;-<span class="st"> </span><span class="kw">gather</span>(year_avgs, contaminante, value, <span class="dv">3</span><span class="op">:</span><span class="kw">length</span>(year_avgs)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">                    </span><span class="kw">filter</span>(<span class="op">!</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias) 
                             <span class="op">&amp;</span><span class="st"> </span>year <span class="op">==</span><span class="st"> &#39;2006&#39;</span> <span class="op">&amp;</span><span class="st"> </span>
<span class="st">                               </span>contaminante <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;BEN&#39;</span>, <span class="st">&#39;MXIL&#39;</span>, <span class="st">&#39;TOL&#39;</span>))) <span class="op">%&gt;%</span>
<span class="st">                                </span><span class="co"># We filter this data because is only completed in 0.01%</span>
<span class="st">                    </span><span class="kw">filter</span>(<span class="op">!</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias) <span class="op">&amp;</span>
<span class="st">                              </span>year <span class="op">==</span><span class="st"> &#39;2008&#39;</span> <span class="op">&amp;</span><span class="st"> </span>contaminante <span class="op">==</span><span class="st"> &#39;PM25&#39;</span>))
                                <span class="co"># We filter this data because is only completed in 0.02%</span>

<span class="co"># We present the data in a grid of graphs</span>

<span class="kw">ggplot</span>(year_avgs_long, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_grid</span>(contaminante<span class="op">~</span>station_alias,<span class="dt">scales=</span><span class="st">&quot;free_y&quot;</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">6</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-45-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We calcule the hourly mean of the pollutants levels.</span>
hour_avgs &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(station_alias, hour, PM10, PM25, SO2, NO2, NO, O3, BEN, CO, MXIL, TOL) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(station_alias, hour) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">funs</span>(<span class="kw">mean</span>(., <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)))  <span class="co"># quito ahora esta variable, porque no tiene sentido que salga su media.</span>

<span class="co"># We convert the table to long format</span>

hour_avgs_long &lt;-<span class="st"> </span><span class="kw">gather</span>(hour_avgs, contaminante, value, <span class="dv">3</span><span class="op">:</span><span class="kw">length</span>(hour_avgs))

<span class="co"># We present the data in a grid of graphs</span>

<span class="kw">ggplot</span>(hour_avgs_long, <span class="kw">aes</span>(<span class="dt">x =</span> hour, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_grid</span>(contaminante<span class="op">~</span>station_alias,<span class="dt">scales=</span><span class="st">&quot;free_y&quot;</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">6</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-46-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We calcule the monthly mean of the pollutants levels.</span>
month_avgs &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(station_alias, month, PM10, PM25, SO2, NO2, NO, O3, BEN, CO, MXIL, TOL) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(station_alias, month) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">funs</span>(<span class="kw">mean</span>(., <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)))  <span class="co"># quito ahora esta variable, porque no tiene sentido que salga su media.</span>

<span class="co"># We convert the table to long format</span>

month_avgs_long &lt;-<span class="st"> </span><span class="kw">gather</span>(month_avgs, contaminante, value, <span class="dv">3</span><span class="op">:</span><span class="kw">length</span>(month_avgs))

<span class="co"># We present the data in a grid of graphs</span>

<span class="kw">ggplot</span>(month_avgs_long, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_grid</span>(contaminante<span class="op">~</span>station_alias,<span class="dt">scales=</span><span class="st">&quot;free_y&quot;</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">6</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We calcule the weekly mean of the pollutants levels.</span>
week_day_avgs &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(station_alias, week_day, PM10, PM25, SO2, NO2, NO, O3, BEN, CO, MXIL, TOL) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(station_alias, week_day) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(<span class="kw">funs</span>(<span class="kw">mean</span>(., <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)))  <span class="co"># quito ahora esta variable, porque no tiene sentido que salga su media.</span>

<span class="co"># We convert the table to long format</span>

week_day_avgs_long &lt;-<span class="st"> </span><span class="kw">gather</span>(week_day_avgs, contaminante, value, <span class="dv">3</span><span class="op">:</span><span class="kw">length</span>(week_day_avgs))

<span class="co"># We present the data in a grid of graphs</span>

<span class="kw">ggplot</span>(week_day_avgs_long, <span class="kw">aes</span>(<span class="dt">x =</span> week_day, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_grid</span>(contaminante<span class="op">~</span>station_alias,<span class="dt">scales=</span><span class="st">&quot;free_y&quot;</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">6</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-48-1.png" width="\textwidth" /></p>
<div id="pm10-constitucion-station" class="section level2">
<h2><span class="header-section-number">7.1</span> PM10 Constitucion Station</h2>
<p>We create the dataset pm10 with PM10 values from the Constitución Station and we execute a summary</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm10 &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(station <span class="op">==</span><span class="st"> &#39;1&#39;</span>) <span class="op">%&gt;%</span>
<span class="st">                        </span><span class="kw">select</span>(date_time_utc, PM10)

<span class="kw">summary</span>(pm10)</code></pre></div>
<pre><code>##  date_time_utc                      PM10       
##  Min.   :2000-01-01 00:00:00   Min.   :  0.00  
##  1st Qu.:2004-06-30 23:15:00   1st Qu.: 19.00  
##  Median :2009-01-02 00:30:00   Median : 29.00  
##  Mean   :2008-12-31 18:50:45   Mean   : 34.39  
##  3rd Qu.:2013-07-02 23:45:00   3rd Qu.: 44.00  
##  Max.   :2017-12-31 23:00:00   Max.   :888.00  
##                                NA&#39;s   :3106</code></pre>
<p>25% of the values are between 44.00 and 888.00. 888.00 is a value really extreme. How many extreme values (outliers) do we have in this series? We plot all the values to visualise this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(pm10, <span class="kw">aes</span>(<span class="dt">x =</span> date_time_utc, <span class="dt">y =</span> PM10)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="\textwidth" /> We have very few values greater than 250. So, it doesn’t seem we have a problem with the outliers.</p>
<p>We filter out the most extreme values to improve the visualization, but</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm10_no_outliers &lt;-<span class="st"> </span>pm10 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(PM10 <span class="op">&lt;=</span><span class="st"> </span><span class="dv">300</span>)
<span class="kw">ggplot</span>(pm10_no_outliers, <span class="kw">aes</span>(<span class="dt">x =</span> date_time_utc, <span class="dt">y =</span> PM10)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-51-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(pm10, <span class="kw">aes</span>(<span class="dt">x =</span> date_time_utc, <span class="dt">y =</span> PM10)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>, <span class="dt">size =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">          </span><span class="kw">scale_y_continuous</span>(<span class="dt">trans=</span><span class="st">&#39;log2&#39;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-52-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PM10_<span class="dv">2017</span> &lt;-<span class="st"> </span>pm10 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">year</span>(date_time_utc) <span class="op">==</span><span class="st"> &#39;2017&#39;</span>) 
<span class="kw">ggplot</span>(PM10_<span class="dv">2017</span>, <span class="kw">aes</span>(<span class="dt">x =</span> date_time_utc, <span class="dt">y =</span> PM10)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">          </span><span class="kw">scale_y_continuous</span>(<span class="dt">trans=</span><span class="st">&#39;log2&#39;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-53-1.png" width="\textwidth" /></p>
<p>Daily averages</p>
<p>We create a new dataset with the PM10 daily averages and we plot them in a new graphic. We add a trend line too. There is a clear downward trend in the measurements and we have many fewer extreme values during the last decade. It seems like we have two very clear “epochs” in the data, with a clear change in the data structure starting somewhere around 2009.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm10_day_avg &lt;-<span class="st"> </span>pm10 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(<span class="dt">day =</span> <span class="kw">date</span>(date_time_utc)) <span class="op">%&gt;%</span>
<span class="st">                          </span><span class="kw">summarise</span>(<span class="dt">day_avg =</span> <span class="kw">mean</span>(PM10, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))

<span class="kw">ggplot</span>(pm10_day_avg, <span class="kw">aes</span>(<span class="dt">x =</span> day, <span class="dt">y =</span> day_avg, , <span class="dt">colour =</span> day_avg)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">geom_smooth</span>(<span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">scale_colour_gradientn</span>(<span class="dt">colours =</span> <span class="kw">terrain.colors</span>(<span class="dv">10</span>)) <span class="op">+</span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.9</span>),
                <span class="dt">legend.background =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;transparent&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>), <span class="dt">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">labs</span>(<span class="dt">colour =</span> <span class="st">&quot;PM10 daily average (colour scale)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;PM10 daily average&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;PM10 daily average - 2000-2017 evolution (Constitucion station)&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="\textwidth" /> We plot the same data but through a box plot graph. Now we can see very clearly how since 2009 the behaviour of the data is sustantially different from the precedent years. The PM10 day levels are smaller, the variability is significantly less pronounced and the trend is smoother too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm10_day_avg &lt;-<span class="st"> </span>pm10 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(<span class="dt">day =</span> <span class="kw">date</span>(date_time_utc)) <span class="op">%&gt;%</span>
<span class="st">                          </span><span class="kw">summarise</span>(<span class="dt">day_avg =</span> <span class="kw">mean</span>(PM10, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))

<span class="kw">ggplot</span>(pm10_day_avg, <span class="kw">aes</span>(<span class="dt">y =</span> day_avg, <span class="dt">x =</span> <span class="kw">as.factor</span>(<span class="kw">year</span>(day)), <span class="dt">colour =</span> day_avg)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_boxplot</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="\textwidth" /></p>
<p>We identify a very clear trend through the years on the last graph. But, as we already saw before on the grid graphs there are other things happening at the same time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">year_const &lt;-<span class="st"> </span>year_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;PM10&#39;</span>)
plot1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(year_const, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

month_const &lt;-<span class="st"> </span>month_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;PM10&#39;</span>)
plot2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(month_const, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

week_day_const &lt;-<span class="st"> </span>week_day_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;PM10&#39;</span>)
plot3 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(week_day_const, <span class="kw">aes</span>(<span class="dt">x =</span> week_day, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

hour_const &lt;-<span class="st"> </span>hour_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;PM10&#39;</span>)
plot4 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(hour_const, <span class="kw">aes</span>(<span class="dt">x =</span> hour, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

<span class="kw">grid.arrange</span>(plot1, plot2, plot3, plot4, <span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="\textwidth" /></p>
</div>
<div id="relationships-between-variables" class="section level2">
<h2><span class="header-section-number">7.2</span> Relationships between variables</h2>
<p>The Constitucion Station is the only station with meteorological data. So, we are going to focus our efforts of data exploration on this station.</p>
<p>Reference: <a href="http://www.sthda.com/english/wiki/ggplot2-quick-correlation-matrix-heatmap-r-software-and-data-visualization" class="uri">http://www.sthda.com/english/wiki/ggplot2-quick-correlation-matrix-heatmap-r-software-and-data-visualization</a></p>
<p>Pollutants correlations matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">constitucion_data &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data_rds/constitucion_data.rds&quot;</span>)

### Pollutants correlation matrix

<span class="co"># We select the pollutants variables</span>
pollutants &lt;-<span class="st"> </span>constitucion_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(PM10, PM25, NO2, NO, SO2, CO, O3, MXIL, TOL) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">na.omit</span>()

<span class="co"># We create the pollutants correlation matrix</span>
cor_matrix &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">cor</span>(pollutants), <span class="dv">2</span>)

<span class="co"># We transform the table to long format to be handled by ggplot2</span>
long_cor_matrix &lt;-<span class="st"> </span><span class="kw">melt</span>(cor_matrix)

<span class="co"># Get lower triangle of the correlation matrix</span>
get_lower_tri&lt;-<span class="cf">function</span>(cor_matrix){
  cor_matrix[<span class="kw">upper.tri</span>(cor_matrix)] &lt;-<span class="st"> </span><span class="ot">NA</span>
  <span class="kw">return</span>(cor_matrix)
}
<span class="co"># Get upper triangle of the correlation matrix</span>
get_upper_tri &lt;-<span class="st"> </span><span class="cf">function</span>(cor_matrix){
  cor_matrix[<span class="kw">lower.tri</span>(cor_matrix)]&lt;-<span class="st"> </span><span class="ot">NA</span>
  <span class="kw">return</span>(cor_matrix)
}

upper_tri &lt;-<span class="st"> </span><span class="kw">get_upper_tri</span>(cor_matrix)

<span class="co"># Melt the correlation matrix</span>
<span class="kw">library</span>(reshape2)
long_cor_matrix &lt;-<span class="st"> </span><span class="kw">melt</span>(upper_tri, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)

<span class="co"># Create a ggheatmap</span>
ggheatmap &lt;-<span class="st"> </span><span class="kw">ggplot</span>(long_cor_matrix, <span class="kw">aes</span>(Var2, Var1, <span class="dt">fill =</span> value))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;white&quot;</span>, 
                       <span class="dt">midpoint =</span> <span class="dv">0</span>, <span class="dt">limit =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">space =</span> <span class="st">&quot;Lab&quot;</span>, 
                       <span class="dt">name=</span><span class="st">&quot;Pearson</span><span class="ch">\n</span><span class="st">Correlation&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_minimal</span>()<span class="op">+</span><span class="st"> </span><span class="co"># minimal theme</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>, <span class="dt">vjust =</span> <span class="dv">1</span>, 
                                   <span class="dt">size =</span> <span class="dv">12</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))<span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>()


pollutants_heatmap &lt;-<span class="st"> </span>ggheatmap <span class="op">+</span><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(Var2, Var1, <span class="dt">label =</span> value), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">4</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(
    <span class="dt">axis.title.x =</span> <span class="kw">element_blank</span>(),
    <span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.border =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.background =</span> <span class="kw">element_blank</span>(),
    <span class="dt">axis.ticks =</span> <span class="kw">element_blank</span>(),
    <span class="dt">legend.justification =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),
    <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.6</span>, <span class="fl">0.7</span>),
    <span class="dt">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="kw">guide_colorbar</span>(<span class="dt">barwidth =</span> <span class="dv">7</span>, <span class="dt">barheight =</span> <span class="dv">1</span>,
                               <span class="dt">title.position =</span> <span class="st">&quot;top&quot;</span>, <span class="dt">title.hjust =</span> <span class="fl">0.5</span>))

<span class="kw">print</span>(pollutants_heatmap)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-57-1.png" width="\textwidth" /></p>
<p>Pollutants-weather data correlations matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">constitucion_data &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;data_rds/constitucion_data.rds&quot;</span>)

### Pollutants correlation matrix

<span class="co"># We select the pollutants variables</span>
pollutants_weather &lt;-<span class="st"> </span>constitucion_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(PM10, PM25, NO2, NO, SO2, CO, O3, MXIL, TOL, dd, vv, TMP, PRB, LL, HR, RS) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">na.omit</span>()

<span class="co"># We create the pollutants correlation matrix</span>
cor_matrix &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">cor</span>(pollutants_weather), <span class="dv">2</span>)

<span class="co"># We transform the table to long format to be handled by ggplot2</span>
long_cor_matrix &lt;-<span class="st"> </span><span class="kw">melt</span>(cor_matrix)

<span class="co"># Get lower triangle of the correlation matrix</span>
get_lower_tri&lt;-<span class="cf">function</span>(cor_matrix){
  cor_matrix[<span class="kw">upper.tri</span>(cor_matrix)] &lt;-<span class="st"> </span><span class="ot">NA</span>
  <span class="kw">return</span>(cor_matrix)
}
<span class="co"># Get upper triangle of the correlation matrix</span>
get_upper_tri &lt;-<span class="st"> </span><span class="cf">function</span>(cor_matrix){
  cor_matrix[<span class="kw">lower.tri</span>(cor_matrix)]&lt;-<span class="st"> </span><span class="ot">NA</span>
  <span class="kw">return</span>(cor_matrix)
}

upper_tri &lt;-<span class="st"> </span><span class="kw">get_upper_tri</span>(cor_matrix)

<span class="co"># Melt the correlation matrix</span>
<span class="kw">library</span>(reshape2)
long_cor_matrix &lt;-<span class="st"> </span><span class="kw">melt</span>(upper_tri, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)

<span class="co"># Create a ggheatmap</span>
ggheatmap &lt;-<span class="st"> </span><span class="kw">ggplot</span>(long_cor_matrix, <span class="kw">aes</span>(Var2, Var1, <span class="dt">fill =</span> value))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;white&quot;</span>, 
                       <span class="dt">midpoint =</span> <span class="dv">0</span>, <span class="dt">limit =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">space =</span> <span class="st">&quot;Lab&quot;</span>, 
                       <span class="dt">name=</span><span class="st">&quot;Pearson</span><span class="ch">\n</span><span class="st">Correlation&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_minimal</span>()<span class="op">+</span><span class="st"> </span><span class="co"># minimal theme</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>, <span class="dt">vjust =</span> <span class="dv">1</span>, 
                                   <span class="dt">size =</span> <span class="dv">12</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))<span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>()


pollutants_heatmap &lt;-<span class="st"> </span>ggheatmap <span class="op">+</span><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(Var2, Var1, <span class="dt">label =</span> value), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(
    <span class="dt">axis.title.x =</span> <span class="kw">element_blank</span>(),
    <span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.border =</span> <span class="kw">element_blank</span>(),
    <span class="dt">panel.background =</span> <span class="kw">element_blank</span>(),
    <span class="dt">axis.ticks =</span> <span class="kw">element_blank</span>(),
    <span class="dt">legend.justification =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>),
    <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.6</span>, <span class="fl">0.7</span>),
    <span class="dt">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="kw">guide_colorbar</span>(<span class="dt">barwidth =</span> <span class="dv">7</span>, <span class="dt">barheight =</span> <span class="dv">1</span>,
                               <span class="dt">title.position =</span> <span class="st">&quot;top&quot;</span>, <span class="dt">title.hjust =</span> <span class="fl">0.5</span>))

<span class="kw">print</span>(pollutants_heatmap)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-58-1.png" width="\textwidth" /></p>
</div>
<div id="no2-constitucion-station" class="section level2">
<h2><span class="header-section-number">7.3</span> NO2 Constitucion Station</h2>
<p>We create the dataset pm10 with PM10 values from the Constitución Station and we execute a summary</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NO2 &lt;-<span class="st"> </span>air_data_<span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(station <span class="op">==</span><span class="st"> &#39;1&#39;</span>) <span class="op">%&gt;%</span>
<span class="st">                        </span><span class="kw">select</span>(date_time_utc, NO2)

<span class="kw">summary</span>(NO2)</code></pre></div>
<pre><code>##  date_time_utc                      NO2        
##  Min.   :2000-01-01 00:00:00   Min.   :  0.00  
##  1st Qu.:2004-06-30 23:15:00   1st Qu.: 20.00  
##  Median :2009-01-02 00:30:00   Median : 34.00  
##  Mean   :2008-12-31 18:50:45   Mean   : 37.26  
##  3rd Qu.:2013-07-02 23:45:00   3rd Qu.: 51.00  
##  Max.   :2017-12-31 23:00:00   Max.   :408.00  
##                                NA&#39;s   :2930</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NO2_day_avg &lt;-<span class="st"> </span>NO2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(<span class="dt">day =</span> <span class="kw">date</span>(date_time_utc)) <span class="op">%&gt;%</span>
<span class="st">                          </span><span class="kw">summarise</span>(<span class="dt">day_avg =</span> <span class="kw">mean</span>(NO2, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))

<span class="kw">ggplot</span>(NO2_day_avg, <span class="kw">aes</span>(<span class="dt">x =</span> day, <span class="dt">y =</span> day_avg, , <span class="dt">colour =</span> day_avg)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">geom_smooth</span>(<span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">scale_colour_gradientn</span>(<span class="dt">colours =</span> <span class="kw">terrain.colors</span>(<span class="dv">10</span>)) <span class="op">+</span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.9</span>),
                <span class="dt">legend.background =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;transparent&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>), <span class="dt">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>) <span class="op">+</span>
<span class="st">         </span><span class="kw">labs</span>(<span class="dt">colour =</span> <span class="st">&quot;PM10 daily average (colour scale)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;PM10 daily average&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;NO2 daily average - 2000-2017 evolution (Constitucion station)&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-60-1.png" width="\textwidth" /></p>
<p>significantly less pronounced and the trend is smoother too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NO2_day_avg &lt;-<span class="st"> </span>NO2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(<span class="dt">day =</span> <span class="kw">date</span>(date_time_utc)) <span class="op">%&gt;%</span>
<span class="st">                          </span><span class="kw">summarise</span>(<span class="dt">day_avg =</span> <span class="kw">mean</span>(NO2, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))

<span class="kw">ggplot</span>(NO2_day_avg, <span class="kw">aes</span>(<span class="dt">y =</span> day_avg, <span class="dt">x =</span> <span class="kw">as.factor</span>(<span class="kw">year</span>(day)), <span class="dt">colour =</span> day_avg)) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">geom_boxplot</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-61-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">year_const &lt;-<span class="st"> </span>year_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;NO2&#39;</span>)
plot1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(year_const, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

month_const &lt;-<span class="st"> </span>month_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;NO2&#39;</span>)
plot2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(month_const, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

week_day_const &lt;-<span class="st"> </span>week_day_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;NO2&#39;</span>)
plot3 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(week_day_const, <span class="kw">aes</span>(<span class="dt">x =</span> week_day, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

hour_const &lt;-<span class="st"> </span>hour_avgs_long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">grepl</span>(<span class="st">&#39;Constit&#39;</span>, station_alias), contaminante <span class="op">==</span><span class="st"> &#39;NO2&#39;</span>)
plot4 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(hour_const, <span class="kw">aes</span>(<span class="dt">x =</span> hour, <span class="dt">y =</span> value)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>()

<span class="kw">grid.arrange</span>(plot1, plot2, plot3, plot4, <span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-62-1.png" width="\textwidth" /></p>
<p>Wind visualizations</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">windRose</span>(air_data_<span class="dv">2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-63-1.png" width="\textwidth" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pollutionRose</span>(air_data_<span class="dv">2</span>, <span class="dt">pollutant =</span> <span class="st">&quot;PM10&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="\textwidth" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="gathering-and-cleaning-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="forecasting-models-arima.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
