---
title: "Gijon Air Pollution - Gathering and Cleaning Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Project goals:

  - Construct a web dashboard to visualize the evolution of the main air pollution indicators of Gijon city. (Asturias; Spain).
  - Build a model to predict in the short term (<24h) the evolution of air pollutants concentration by monitoring station.

### Data gathering

Loading packages
```{r , warning= FALSE, message= FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(openair) # http://davidcarslaw.github.io/openair/
library(purrr)
library(lubridate)
library(ggplot2)
library(stringr)
library(knitr)
library(xts)
library(zoo)
library(gridExtra)
library(astsa)
library(rvest)
library(fpp2)
library(ranger)
library(broom)
library(RcppRoll)
library(reticulate)


```


```{r setup, include=FALSE}
use_python("/usr/local/bin/python")
```

```{python}
import pandas as pd
flights = pd.read_csv("flights.csv")
```